[build]
builder = "nixpacks"

[variables]
PORT = "8000"

[phases.setup]
nixPkgs = ["python310Full"]

[phases.build]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[phases.start]
cmd = "python manage.py runserver 0.0.0.0:$PORT"


