[phases.setup]
nixPkgs = ["python310", "pipenv", "postgresql"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = []

[phases.start]
cmd = "python manage.py migrate && python manage.py runserver 0.0.0.0:$PORT"


