POST http://127.0.0.1:8000/login HTTP/1.1
Content-Type: application/json

{
  "username": "neero_bracu",
  "password": "Amdrx4800%%%",
  "email": "shamrat.neero@g.bracu.ac.bd"
}

###


POST http://127.0.0.1:8000/signup HTTP/1.1
Content-Type: application/json

{
  "username": "test7",
  "password": "Pass1234!",
  "email": "test@test.com"
}


###

POST http://127.0.0.1:8000/test_token

Content-Type: application/json

{}

###

POST http://127.0.0.1:8000/logout/ HTTP/1.1
Content-Type: application/json

{
}






